<?php

namespace App\Http\Controllers;

use App\Models\Crime;
use App\Models\Application;
use Illuminate\Http\Request;
use SimpleSoftwareIO\QrCode\Facades\QrCode;
use Illuminate\Support\Facades\Storage;
class CrimeController extends Controller
{
    public function index()
    {
        $applications = Application::with('applicant')->get();
        $crimes = Crime::all(); // All crime records

        return view('crimes.index', compact('applications', 'crimes'));
    }



public function check(Application $application)
{
    // Check if crime exists
    $crime = Crime::where('application_id', $application->id)
                  ->orWhere('phone', $application->applicant->Phone ?? null)
                  ->first();

    // if($crime) {
    //      dd($crime);
    //     return back()->with('found', $crime->status);
    // }

   
    // Create new crime record
    $crime = Crime::create([
        'application_id' => $application->id,
        'phone' => $application->applicant->Phone ?? null,
        'status' => 'verified',
    ]);

    // Generate certificate for this application
    $certificateNumber = 'CERT-' . strtoupper(uniqid());
    $issueDate = now();
    $expiryDate = now()->addYears(1);
    
    // // Generate QR code image for the certificate
    // $qrFileName = 'certificate_qr_' . $application->id . '.png';
    // $qrPath = 'public/certificates/qrcodes/' . $qrFileName;
    // Storage::put($qrPath, QrCode::format('png')->size(200)->generate($certificateNumber));

    // Optional: Digital signature placeholder (could be image path or text)
    $digitalSignature = 'Generated by Police System';

    \App\Models\Certificate::create([
        'application_id' => $application->id,
        'certificate_number' => $certificateNumber,
        'issue_date' => $issueDate,
        'expiry_date' => $expiryDate,
        'qr_code_path' => 'storage/certificates/qrcodes/',
        'status' => 'active',
        'digital_signature' => $digitalSignature,
    ]);

    return back()->with('success', 'Crime certificate generated successfully with QR code.');
}


}
